defmodule InstaCloneWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :insta_clone

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_insta_clone_key",
    signing_salt: "Y66KjNxS",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :insta_clone,
    gzip: not code_reloading?,
    only: InstaCloneWeb.static_paths()

  # Serve runtime-uploaded files (images, stories, etc.) directly from the
  # filesystem path. The `from:` using :otp_app above only covers files that
  # exist at compile time; this second plug covers files written at runtime.
  plug Plug.Static,
    at: "/images",
    from: Path.join([:code.priv_dir(:insta_clone), "static", "images"]),
    gzip: false

  plug Plug.Static,
    at: "/logos",
    from: Path.join([:code.priv_dir(:insta_clone), "static", "logos"]),
    gzip: false

  # Story uploads go here — outside priv/static/ so dev live-reload doesn't loop
  plug Plug.Static,
    at: "/uploads",
    from: Path.join([:code.priv_dir(:insta_clone), "uploads"]),
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :insta_clone
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug InstaCloneWeb.Router
end
